language: node_js
node_js:
  - node
dist: trusty
os: linux
services:
  - mongodb
  - redis
env:
  - NODE_ENV=ci
  - PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
  - npm audit fix
script:
  - nohup npm run start &
  - sleep 10
  - npm run test